apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-backend
  namespace: kiii-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiii-backend
  template:
    metadata:
      labels:
        app: kiii-backend
    spec:
      containers:
        - name: kiii-backend
          image: milagjorgoska/kiii-project-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-password
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_HOST
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_DB
---
apiVersion: v1
kind: Service
metadata:
  name: kiii-backend-service
  namespace: kiii-ns
spec:
  selector:
    app: kiii-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
