apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-frontend
  namespace: kiii-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kiii-frontend
  template:
    metadata:
      labels:
        app: kiii-frontend
    spec:
      containers:
        - name: kiii-frontend
          image: milagjorgoska/kiii-project-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kiii-frontend-service
  namespace: kiii-ns
spec:
  selector:
    app: kiii-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
