apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiii-ingress
  namespace: kiii-ns
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: kiii-app.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: kiii-backend-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kiii-frontend-service
                port:
                  number: 80
